- hosts: local
  tasks:
    - replace:
        path: hosts
        regexp: '^\[{{ item.category }}\]\s(.*)host(.*)$'
        replace: '[{{ item.category }}]\n  host=[{{ item.host }}]'
      with_items:
        - { category: 'kubernetes-master-nodes', host: 'http://cake.com:8080' }
