apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-volume
 labels:
   type: local
   app: postgres
spec:
 storageClassName: manual
 capacity:
   storage: 5Gi
 accessModes:
   - ReadWriteMany
 hostPath:
   path: "/mnt/db"
