heat_template_version: 2017-09-01
#quota management for keystone user
resources:
  test_role:
    type: OS::Keystone::Role
    properties:
      name: test_role1

  test_project:
    type: OS::Keystone::Project
    properties:
      name: test_project1
      enabled: True

  test_user:
    type: OS::Keystone::User
    properties:
      name: test_user1
      domain: default
      default_project: {get_resource: test_project}
      roles:
        - role: {get_resource: test_role}
          domain: default
        - role: {get_resource: test_role}
          project: {get_resource: test_project}

  nova_user_quota:
    type: OS::Nova::Quota
    properties:
      project: {get_resource: test_project}
      cores: 5
      fixed_ips: 5
      floating_ips: 5
      instances: 5
      injected_files: 5
      injected_file_content_bytes: 5
      injected_file_path_bytes: 5
      key_pairs: 5
      metadata_items: 5
      ram: 5
      security_groups: 5
      security_group_rules: 5
      server_groups: 5
      server_group_members: 5

outputs:
  nova_user_quota_id:
    value: {get_resource: nova_user_quota}
