--- 
- 
  hosts: all
  tasks: 
    - 
      apt: 
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - vim
          - software-properties-common
        state: present
      name: "Installing Prerequisites for Kubernetes"
    - 
      apt_key: 
        state: present
        url: "https://download.docker.com/linux/ubuntu/gpg"
      name: "Add Docker’s official GPG key"
    - 
      apt_repository: 
        filename: docker
        mode: 384
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
        state: present
      name: "Add Docker Repository"
    - 
      apt: 
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      name: "Install Docker Engine."
    - 
      name: "Enable service docker, and enable persistently"
      service: 
        enabled: true
        name: docker
    - 
      apt_key: 
        state: present
        url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
      name: "Add Google official GPG key"
    - 
      apt_repository: 
        filename: kubernetes
        mode: 384
        repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
      name: "Add Kubernetes Repository"
    - 
      apt: 
        name: 
          - kubeadm
          - kubectl
          - kubelet
        state: present
      name: "Installing Kubernetes Cluster Packages."
    - 
      name: "Enable service kubelet, and enable persistently"
      service: 
        enabled: true
        name: kubelet

